# -*- coding: utf-8 -*-
"""sementic-search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DWZZQh3n3PD6OREWNTY2uc4pC48cNP9
"""

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import numpy as np

name_list = [
    "Ahmed", "Ali", "Hassan", "Omar", "Yusuf",
    "Ibrahim", "Imran", "Farhan", "Saad", "Zayd"
]

model = SentenceTransformer('all-MiniLM-L6-v2')

name_embeddings = model.encode(name_list, convert_to_tensor=True)

len(name_embeddings)

query = input("Enter your search query: ")
query_embedding = model.encode(query, convert_to_tensor=True)
cosine_scores = util.cos_sim(query_embedding, name_embeddings)

top_result_index = cosine_scores.argmax()
print(f"\nMost semantically similar name to '{query}': {name_list[top_result_index]}")

top_3 = cosine_scores.topk(3)
print("\nTop 3 names with similarity scores:")
for idx, score in zip(top_3[1][0], top_3[0][0]):
    print(f"{name_list[idx]} - Score: {score:.4f}")





names = [
    {"name": "Muhammad", "meaning": "Highly praised"},
    {"name": "Ahmed", "meaning": "Most praised"},
    {"name": "Ali", "meaning": "High, noble"},
    {"name": "Omar", "meaning": "Long life"},
    {"name": "Yusuf", "meaning": "God will increase"},
    {"name": "Ibrahim", "meaning": "Father of nations"},
    {"name": "Musa", "meaning": "Drawn from water"},
    {"name": "Adam", "meaning": "Man of earth"},
    {"name": "Idris", "meaning": "Studious"},
    {"name": "Nuh", "meaning": "Rest"},
    {"name": "Harun", "meaning": "Strong"},
    {"name": "Sulaiman", "meaning": "Peaceful"},
    {"name": "Dawood", "meaning": "Beloved"},
    {"name": "Isa", "meaning": "God is salvation"},
    {"name": "Hasan", "meaning": "Handsome"},
    {"name": "Husain", "meaning": "Beautiful"},
    {"name": "Hamza", "meaning": "Lion"},
    {"name": "Bilal", "meaning": "Water"},
    {"name": "Khalid", "meaning": "Eternal"},
    {"name": "Jamal", "meaning": "Beauty"},
    {"name": "Karim", "meaning": "Generous"},
    {"name": "Rashid", "meaning": "Rightly guided"},
    {"name": "Samir", "meaning": "Entertaining friend"},
    {"name": "Tariq", "meaning": "Morning star"},
    {"name": "Zain", "meaning": "Beautiful"},
    {"name": "Faris", "meaning": "Knight"},
    {"name": "Rayyan", "meaning": "Gates of heaven"},
    {"name": "Ayan", "meaning": "Gift of God"},
    {"name": "Arham", "meaning": "Merciful"},
    {"name": "Malik", "meaning": "King"},
    {"name": "Qasim", "meaning": "Divider"},
    {"name": "Rahim", "meaning": "Compassionate"},
    {"name": "Saleh", "meaning": "Righteous"},
    {"name": "Tahir", "meaning": "Pure"},
    {"name": "Wahid", "meaning": "Unique"},
    {"name": "Zakir", "meaning": "One who remembers God"},
    {"name": "Amin", "meaning": "Trustworthy"},
    {"name": "Jamil", "meaning": "Beautiful"},
    {"name": "Kamal", "meaning": "Perfect"},
    {"name": "Latif", "meaning": "Gentle"}
]

names

df = pd.DataFrame(names)
print(len(df))
df.head(10)

# preparing data for sementic search
names = df['name'].tolist()
meanings_list = df['meaning'].tolist()
combined_texts = [f"{name} - {meaning}" for name, meaning in zip(names, meanings_list)]

# converting names and meanings to vector
embeddings = model.encode(combined_texts, convert_to_tensor=True)
print(f"\n Converted {len(embeddings)} names to vectors")

embeddings.shape

# creating search function for sementic search
def search_names(query, top_k=4):

    print(f"\n Searching for: '{query}'")

    query_embedding = model.encode(query, convert_to_tensor=True)
    # Calculate similarity scores
    cos_scores = util.cos_sim(query_embedding, embeddings)[0]

    # Get top results
    top_results = np.argsort(-cos_scores.cpu().numpy())[:top_k]
    for i, idx in enumerate(top_results, 1):
        name = names[idx]
        meaning = meanings_list[idx]
        score = cos_scores[idx].item()

        print(f"{i}. {name}")
        print(f"   Meaning: {meaning}")
        print(f"   Match score: {score:.3f}")

    return top_results

print("test 1: Search for names meaning 'beautiful'")
search_names("beautiful handsome good looking")

print("\ntest 2: Search for names meaning 'strong'")
search_names("strong powerful lion brave")

print("\ntest 3: Search for names meaning 'king'")
search_names("king ruler leader")

print("\n test 4: Search for names meaning 'pure'")
search_names("pure clean innocent")

# interactive search
def interactive_search():
    query = input("\nWhat name meaning are you looking for? (e.g., 'wise', 'kind', 'leader'): ")
    if query.strip():
        search_names(query, top_k=8)

# finding similer names
def find_similar_names(given_name, top_k=5):
    print(f"\n finding names similar to: '{given_name}'")
    if given_name not in names:
        print(f"'{given_name}' not found in our list.")
        return
    idx = names.index(given_name)

    cos_scores = util.cos_sim(embeddings[idx], embeddings)[0]

    top_results = np.argsort(-cos_scores.cpu().numpy())[1:top_k+1]

    for i, result_idx in enumerate(top_results, 1):
        name = names[result_idx]
        meaning = meanings_list[result_idx]
        score = cos_scores[result_idx].item()

        print(f"{i}. {name} - {meaning} (Score: {score:.3f})")

print("\n finding names similar to 'Muhammad':")
find_similar_names("Muhammad")

print("\n finding names similar to 'Ali':")
find_similar_names("Ali")

